# ~/.config/hypr/hyprland.conf

# Source Color configuration
source = ~/.config/hypr/myColors.conf

# Source Modular Configuration Files
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/look_and_feel.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/keybinds.conf

xwayland {
  force_zero_scaling = true
}

# Plugins
plugin:dynamic-cursors {
    enabled = false
    mode = tilt
    shake {
        enabled = true
        nearest = true
    }
}
