# ~/.config/hypr/conf/autostart.conf
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
exec-once = swaync
exec-once = awww-daemon
exec-once = swayosd-server
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = hyprpm reload
exec-once = while true; do ~/.config/hypr/scripts/wallpaper.sh; sleep 1800; done
