# ~/.config/hypr/conf/programs.conf
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$browser = zen-browser
$wallpaper_shuffle = ~/.config/hypr/scripts/wallpaper.sh
$telegram = telegram-desktop
